package com.riiablo.map;

import com.artemis.annotations.Wire;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.math.MathUtils;
import com.badlogic.gdx.utils.Array;
import com.badlogic.gdx.utils.IntMap;
import com.riiablo.Riiablo;
import com.riiablo.codec.excel.Levels;
import com.riiablo.codec.excel.LvlPrest;
import com.riiablo.engine.server.NativeDataTables;
import com.riiablo.engine.EntityFactory;
import com.riiablo.engine.server.quest.Act2TombSelection;
import com.riiablo.map.Map.Preset;
import com.riiablo.map.Map.Zone;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Act2 地图生成器 - 完全复刻 D2MOD 实现
 * 
 * 参考 D2MOD:
 * - source/D2Common/src/Drlg/DrlgOutPlace.cpp (gAct2OutdoorDrlgLink, gAct2CanyonDrlgLink)
 * - source/D2Common/src/Drlg/DrlgOutDesr.cpp (DRLGOUTDESR_InitAct2OutdoorLevel)
 */
public enum Act2MapBuilderD2MOD implements MapBuilder {
  INSTANCE;

  private static final String TAG = "Act2MapBuilderD2MOD";
  private static final boolean DEBUG = true;
  private static final boolean DEBUG_BUILD = DEBUG && true;

  // D2MOD: gAct2OutdoorDrlgLink 数组
  private static final int LEVEL_LUTGHOLEIN = 40;
  private static final int LEVEL_ROCKYWASTE = 41;
  private static final int LEVEL_DRYHILLS = 42;
  private static final int LEVEL_FAROASIS = 43;
  private static final int LEVEL_LOSTCITY = 44;
  private static final int LEVEL_VALLEYOFSNAKES = 45;
  private static final int LEVEL_CANYONOFTHEMAGI = 46;
  private static final int LEVEL_ARCANESANCTUARY = 75;
  private static final int ACT2_LEVEL_FIRST = LEVEL_LUTGHOLEIN;
  private static final int ACT2_LEVEL_LAST = LEVEL_ARCANESANCTUARY;
  private static final int DUNGEON_PLACEMENT_GAP = 10 * DT1.Tile.SUBTILE_SIZE;

  /**
   * D2Common's Act II outdoor link order.  The native generator does not
   * replace the Levels.txt arrays; DRLG_SetWarpId appends these links to the
   * first empty runtime slot.  Keep the order identical so special wall main
   * indices produced by native DS1 exports resolve to the same destination.
   */
  private static final int[][] ACT2_OUTDOOR_LINKS = {
      {LEVEL_LUTGHOLEIN, LEVEL_ROCKYWASTE},
      {LEVEL_ROCKYWASTE, LEVEL_DRYHILLS},
      {LEVEL_DRYHILLS, LEVEL_FAROASIS},
      {LEVEL_FAROASIS, LEVEL_LOSTCITY},
      {LEVEL_LOSTCITY, LEVEL_VALLEYOFSNAKES},
      // Canyon is generated by gAct2CanyonDrlgLink, but is the playable
      // continuation of Valley of Snakes and must be reachable in riiablo.
      {LEVEL_VALLEYOFSNAKES, LEVEL_CANYONOFTHEMAGI}
  };

  @Wire(name = "factory")
  protected EntityFactory factory;

  @Wire(name = "client.socket", failOnNull = false)
  protected com.badlogic.gdx.net.Socket socket;

  /**
   * D2MOD: sub_6FD81B30 - 处理 ROCKYWASTE 的放置
   */
  private boolean placeRockyWaste(BaseMapBuilderD2MOD.LevelLinkData linkData, int iteration) {
    if (linkData.rand[1][iteration] == -1) {
      linkData.rand[1][iteration] = MathUtils.random.nextInt() & 3; // 0-3
      linkData.rand[0][iteration] = linkData.rand[1][iteration];
    } else {
      int nextRand = (linkData.rand[0][iteration] + 1) % 4;
      if (nextRand == linkData.rand[1][iteration]) {
        return false; // 回溯
      }
      linkData.rand[0][iteration] = nextRand;
    }

    int levelLink = linkData.links[iteration].levelLink;
    BaseMapBuilderD2MOD base = new BaseMapBuilderD2MOD() {};
    base.calculateCoordOffset(linkData.coords[levelLink], linkData.coords[iteration], linkData.rand[0][iteration], 0);
    return true;
  }

  /**
   * D2MOD: sub_6FD81530 - 处理 DRYHILLS, FAROASIS, LOSTCITY 的放置
   */
  private boolean placeDesertArea(BaseMapBuilderD2MOD.LevelLinkData linkData, int iteration) {
    if (linkData.rand[1][iteration] == -1) {
      linkData.rand[1][iteration] = MathUtils.random.nextInt() & 3; // 0-3
      linkData.rand[0][iteration] = linkData.rand[1][iteration];
    } else {
      int nextRand = (linkData.rand[0][iteration] + 1) % 4;
      if (nextRand == linkData.rand[1][iteration]) {
        return false; // 回溯
      }
      linkData.rand[0][iteration] = nextRand;
    }

    int levelLink = linkData.links[iteration].levelLink;
    BaseMapBuilderD2MOD base = new BaseMapBuilderD2MOD() {};
    base.calculateCoordOffsetAlt(linkData.coords[levelLink], linkData.coords[iteration], linkData.rand[0][iteration], 1);
    return true;
  }

  /**
   * D2MOD: sub_6FD81BF0 - 处理 VALLEYOFSNAKES 的放置
   */
  private boolean placeValleyOfSnakes(BaseMapBuilderD2MOD.LevelLinkData linkData, int iteration) {
    if (linkData.rand[1][iteration] == -1) {
      linkData.rand[1][iteration] = MathUtils.random.nextInt() & 3; // 0-3
      linkData.rand[0][iteration] = linkData.rand[1][iteration];
    } else {
      int nextRand = (linkData.rand[0][iteration] + 1) % 4;
      if (nextRand == linkData.rand[1][iteration]) {
        return false; // 回溯
      }
      linkData.rand[0][iteration] = nextRand;
    }

    int levelLink = linkData.links[iteration].levelLink;
    BaseMapBuilderD2MOD base = new BaseMapBuilderD2MOD() {};
    base.calculateCoordOffset(linkData.coords[levelLink], linkData.coords[iteration], linkData.rand[0][iteration], 0);
    return true;
  }

  @Override
  public void generate(Map map, int seed, int diff) {
    // 重要：设置随机种子，确保多人游戏中所有客户端生成相同的地图
    MathUtils.random.setSeed(seed);
    Act2TombSelection tombSelection = Act2TombSelection.forGameSeed(seed);
    Gdx.app.log(TAG, String.format(
        "Act2 native tomb selection: seed=%d staff=%d boss=%d",
        seed, tombSelection.staffTombLevel(), tombSelection.bossTombLevel()));

    // D2MOD: gAct2OutdoorDrlgLink 数组
    // { 函数指针, 区域ID, levelLink, levelLinkEx }
    BaseMapBuilderD2MOD.LevelLink[] act2Links = new BaseMapBuilderD2MOD.LevelLink[] {
      new BaseMapBuilderD2MOD.LevelLink(LEVEL_LUTGHOLEIN, -1, -1),      // 0: 城镇
      new BaseMapBuilderD2MOD.LevelLink(LEVEL_ROCKYWASTE, 0, -1),       // 1
      new BaseMapBuilderD2MOD.LevelLink(LEVEL_DRYHILLS, 1, -1),        // 2
      new BaseMapBuilderD2MOD.LevelLink(LEVEL_FAROASIS, 2, -1),        // 3
      new BaseMapBuilderD2MOD.LevelLink(LEVEL_LOSTCITY, 3, -1),        // 4
      new BaseMapBuilderD2MOD.LevelLink(LEVEL_VALLEYOFSNAKES, 4, -1),   // 5
      null // 结束标记
    };

    BaseMapBuilderD2MOD.LevelLinkData linkData = new BaseMapBuilderD2MOD.LevelLinkData();

    // 初始化区域尺寸（从 Levels.txt 读取）
    for (int i = 0; i < act2Links.length && act2Links[i] != null; i++) {
      linkData.links[i] = act2Links[i];
      Levels.Entry level = Riiablo.files.Levels.get(act2Links[i].level);
      if (level == null) {
        Gdx.app.error(TAG, "Level not found: " + act2Links[i].level);
        continue;
      }
      int sizeX = NativeDataTables.levelSizeX(level, diff, 1);
      int sizeY = NativeDataTables.levelSizeY(level, diff, 1);
      linkData.coords[i].width = sizeX * 5;  // tile to sub-tile
      linkData.coords[i].height = sizeY * 5;
    }

    // D2MOD: sub_6FD823C0 - 主要链接循环
    int counter = 0;
    while (counter < act2Links.length && act2Links[counter] != null) {
      boolean success = false;
      Levels.Entry level = Riiablo.files.Levels.get(act2Links[counter].level);
      if (level == null) {
        Gdx.app.error(TAG, "Level not found: " + act2Links[counter].level);
        break;
      }
      
      // 根据区域类型选择处理函数
      if (act2Links[counter].level == LEVEL_LUTGHOLEIN) {
        // sub_6FD81330 - 第一个区域（城镇），使用 Levels.txt 中的偏移
        BaseMapBuilderD2MOD base = new BaseMapBuilderD2MOD() {};
        success = base.placeFirstLevel(linkData, counter, level);
      } else if (act2Links[counter].level == LEVEL_ROCKYWASTE) {
        // sub_6FD81B30 - ROCKYWASTE
        success = placeRockyWaste(linkData, counter);
      } else if (act2Links[counter].level == LEVEL_DRYHILLS || 
                 act2Links[counter].level == LEVEL_FAROASIS ||
                 act2Links[counter].level == LEVEL_LOSTCITY) {
        // sub_6FD81530 - DRYHILLS, FAROASIS, LOSTCITY
        success = placeDesertArea(linkData, counter);
      } else if (act2Links[counter].level == LEVEL_VALLEYOFSNAKES) {
        // sub_6FD81BF0 - VALLEYOFSNAKES
        success = placeValleyOfSnakes(linkData, counter);
      } else {
        // 未知区域类型，使用默认逻辑
        if (act2Links[counter].levelLink >= 0) {
          int levelLink = act2Links[counter].levelLink;
          linkData.coords[counter].x = linkData.coords[levelLink].x + linkData.coords[levelLink].width;
          linkData.coords[counter].y = linkData.coords[levelLink].y;
          success = true;
        } else {
          linkData.coords[counter].x = level.OffsetX;
          linkData.coords[counter].y = level.OffsetY;
          success = true;
        }
      }

      // 检查重叠（参考 DRLGOUTPLACE_LinkAct2Outdoors）
      BaseMapBuilderD2MOD base = new BaseMapBuilderD2MOD() {};
      if (success && base.checkNotOverlapping(linkData, counter, linkData.links[counter].levelLink)) {
        counter++;
      } else {
        // 回溯：重置随机数
        linkData.rand[0][counter] = -1;
        linkData.rand[1][counter] = -1;
        linkData.rand[2][counter] = -1;
        linkData.rand[3][counter] = -1;
        counter--;
        if (counter < 0) {
          Gdx.app.error(TAG, "Failed to generate map after backtracking");
          return;
        }
      }
    }

    // 找到城镇（LUTGHOLEIN）的索引，用于计算坐标偏移
    int townIndex = -1;
    for (int i = 0; i < act2Links.length && act2Links[i] != null; i++) {
      if (act2Links[i].level == LEVEL_LUTGHOLEIN) {
        townIndex = i;
        break;
      }
    }
    
    // 计算坐标偏移，使城镇在 (0, 0) 附近
    int offsetX = 0;
    int offsetY = 0;
    if (townIndex >= 0) {
      offsetX = -linkData.coords[townIndex].x;
      offsetY = -linkData.coords[townIndex].y;
    } else {
      offsetX = -linkData.coords[0].x;
      offsetY = -linkData.coords[0].y;
    }
    
    // 创建区域：先创建城镇
    Zone townZone = null;
    for (int i = 0; i < act2Links.length && act2Links[i] != null; i++) {
      if (act2Links[i].level == LEVEL_LUTGHOLEIN) {
        Levels.Entry level = Riiablo.files.Levels.get(act2Links[i].level);
        final int drlgType = level.DrlgType;
        final boolean isPresetLevel = drlgType == 2; // 2 == DRLGTYPE_PRESET

        // 查找与 level 对应的 preset（仅当 DrlgType 为 PRESET 时才整图使用）
        LvlPrest.Entry preset = null;
        if (isPresetLevel) {
          for (LvlPrest.Entry p : Riiablo.files.LvlPrest) {
            if (p.LevelId == act2Links[i].level) {
              preset = p;
              break;
            }
          }
        }

        BaseMapBuilderD2MOD base = new BaseMapBuilderD2MOD() {};
        base.factory = factory;
        base.socket = socket;

        int finalX = linkData.coords[i].x + offsetX;
        int finalY = linkData.coords[i].y + offsetY;

        if (!isPresetLevel || preset == null) {
          // 若不是 PRESET 关卡，则退回随机生成，保持与 D2MOO 一致
          townZone = base.createZoneWithGenerator(map, level, diff, finalX, finalY);
        } else {
          int fileId[] = new int[6];
          int numFiles = Preset.getPresets(preset, fileId);
          if (numFiles == 0) {
            Gdx.app.error(TAG, "No valid presets found for level " + level.LevelName);
            break;
          }
          int selectIndex = MathUtils.random(numFiles - 1);
          int select = fileId[selectIndex];

          if (select < 0 || select >= preset.File.length || 
              preset.File[select] == null || 
              preset.File[select].isEmpty() || 
              preset.File[select].charAt(0) == '0') {
            Gdx.app.error(TAG, "Invalid file index " + select + " for level " + level.LevelName);
            break;
          }

          townZone = base.createZoneWithPreset(map, level, preset, select, finalX, finalY, true);
        }
        break;
      }
    }
    
    // 创建其他区域
    for (int i = 0; i < act2Links.length && act2Links[i] != null; i++) {
      if (act2Links[i].level == LEVEL_LUTGHOLEIN) {
        continue; // 跳过城镇
      }
      
      Levels.Entry level = Riiablo.files.Levels.get(act2Links[i].level);
      if (level == null) {
        Gdx.app.error(TAG, "Level not found: " + act2Links[i].level);
        continue;
      }
      
      // 查找与 level 对应的 preset
      LvlPrest.Entry preset = null;
      for (LvlPrest.Entry p : Riiablo.files.LvlPrest) {
        if (p.LevelId == act2Links[i].level) {
          preset = p;
          break;
        }
      }
      
      Zone zone;
      BaseMapBuilderD2MOD base = new BaseMapBuilderD2MOD() {};
      base.factory = factory;
      base.socket = socket;
      
      int finalX = linkData.coords[i].x + offsetX;
      int finalY = linkData.coords[i].y + offsetY;
      
      final int drlgType = level.DrlgType;
      final boolean isPresetLevel = drlgType == 2; // 2 == DRLGTYPE_PRESET

      if (preset != null && isPresetLevel) {
        int fileId[] = new int[6];
        int numFiles = Preset.getPresets(preset, fileId);
        if (numFiles == 0) {
          Gdx.app.error(TAG, "No valid presets found for level " + level.LevelName);
          continue;
        }
        int selectIndex = MathUtils.random(numFiles - 1);
        int select = fileId[selectIndex];
        
        if (select < 0 || select >= preset.File.length || 
            preset.File[select] == null || 
            preset.File[select].isEmpty() || 
            preset.File[select].charAt(0) == '0') {
          Gdx.app.error(TAG, "Invalid file index " + select + " for level " + level.LevelName);
          continue;
        }
        
        zone = base.createZoneWithPreset(map, level, preset, select, finalX, finalY, false);
      } else {
        zone = base.createZoneWithGenerator(map, level, diff, finalX, finalY);
      }
      
      // 设置怪物生成器
      zone.generator = base.createMonsterGenerator(socket);
    }
    
    // 处理 CANYONOFTHEMAGI。它不是一个脱离主链的固定坐标区域：
    // D2Common 的 gAct2CanyonDrlgLink 把 Canyon 接在 Valley of Snakes
    // 的运行时坐标之后。旧实现直接使用 Levels.OffsetX/OffsetY，虽然
    // Warp 表项存在，但入口会把玩家送到另一块不相连的地图。
    Levels.Entry canyonLevel = Riiablo.files.Levels.get(LEVEL_CANYONOFTHEMAGI);
    if (canyonLevel != null) {
      LvlPrest.Entry canyonPreset = null;
      for (LvlPrest.Entry p : Riiablo.files.LvlPrest) {
        if (p.LevelId == LEVEL_CANYONOFTHEMAGI) {
          canyonPreset = p;
          break;
        }
      }
      
      if (canyonPreset != null) {
        int fileId[] = new int[6];
        int numFiles = Preset.getPresets(canyonPreset, fileId);
        if (numFiles > 0) {
          int selectIndex = MathUtils.random(numFiles - 1);
          int select = fileId[selectIndex];
          BaseMapBuilderD2MOD base = new BaseMapBuilderD2MOD() {};
          base.factory = factory;
          base.socket = socket;

          // linkData[5] is Valley of Snakes, the final outdoor link in
          // gAct2OutdoorDrlgLink.  Use its post-layout coordinate and append
          // Canyon along the native east-facing link.  Keep the fallback for
          // malformed/partial tables so headless tests still get a usable
          // Canyon zone instead of crashing generation.
          int valleyX = linkData.coords[5].x + offsetX;
          int valleyY = linkData.coords[5].y + offsetY;
          int[] canyonPlacement = resolveCanyonPlacement(
              valleyX, valleyY, linkData.coords[5].width,
              canyonLevel.OffsetX, canyonLevel.OffsetY);
          int canyonX = canyonPlacement[0];
          int canyonY = canyonPlacement[1];
          if (canyonPlacement[2] != 0) {
            Gdx.app.error(TAG, "Act2 Valley coordinate unavailable; using Canyon offset fallback");
          }
          Zone canyonZone = base.createZoneWithPreset(map, canyonLevel, canyonPreset,
              select, canyonX, canyonY, false);
          if (canyonZone != null) canyonZone.generator = base.createMonsterGenerator(socket);

          Gdx.app.log(TAG, String.format(
              "Act2 native canyon placement: valley=(%d,%d) canyon=(%d,%d) fallback=%s",
              valleyX, valleyY, canyonX, canyonY, canyonPlacement[2] != 0));
        }
      }
    }

    // Levels.txt contains the Act II underground graph, but the outdoor
    // builder above only creates the seven outdoor links.  D2Common allocates
    // linked dungeon levels lazily from the real Vis/Warp slots.  Do the same
    // here before Warp entities are emitted; otherwise an entrance can be
    // rendered while its destination Zone is missing (black/void map).
    createAct2LinkedDungeonZones(map, diff, seed);

    // Configure the runtime slots before MapManager creates Warp entities.
    // Native D2Common performs this after layout placement via
    // DRLG_SetWarpId; doing it here preserves the same mainIndex semantics.
    configureAct2OutdoorWarps(map);

    // 添加高级功能：边界、路径、传送点、神殿等
    // 参考 D2MOD: DRLGOUTDESR_InitAct2OutdoorLevel
    for (Zone zone : map.zones) {
      if (!zone.town && isAct2OutdoorLevel(zone.level.Id)) {
        // 放置边界
        OutdoorFeatures.placeBorders(zone, seed, 1);
        
        // 放置传送点（特定区域）
        if (zone.level.Id == LEVEL_DRYHILLS || zone.level.Id == LEVEL_FAROASIS || 
            zone.level.Id == LEVEL_LOSTCITY) {
          OutdoorFeatures.placeWaypoint(zone, seed);
        }
        
        // 放置神殿（5个）
        if (zone.level.Id == LEVEL_ROCKYWASTE || zone.level.Id == LEVEL_DRYHILLS ||
            zone.level.Id == LEVEL_FAROASIS || zone.level.Id == LEVEL_LOSTCITY ||
            zone.level.Id == LEVEL_CANYONOFTHEMAGI) {
          OutdoorFeatures.placeShrines(zone, seed, 5);
        }
      }
    }
  }

  /**
   * Creates all Act II levels reachable through a real Levels.txt Vis/Warp
   * edge.  This intentionally does not hard-code Halls/Maggot/Viper/Tomb
   * ids: 1.10f table data is the source of truth and the same routine also
   * handles Palace Cellars, Sewers and Arcane Sanctuary.
   */
  private void createAct2LinkedDungeonZones(Map map, int diff, int seed) {
    if (map == null || Riiablo.files == null || Riiablo.files.Levels == null) return;

    List<Act2WarpEdge> edges = discoverAct2WarpEdges(Riiablo.files.Levels);
    if (edges.isEmpty()) {
      Gdx.app.log(TAG, "Act2 linked dungeon discovery: no Vis/Warp edges in Levels.txt");
      return;
    }

    Set<Integer> generated = new LinkedHashSet<>();
    List<Integer> queue = new ArrayList<>();
    for (Zone zone : map.zones) {
      if (zone != null && zone.level != null && isAct2Level(zone.level.Id)) {
        generated.add(zone.level.Id);
        queue.add(zone.level.Id);
      }
    }

    HashMap<Integer, Levels.Entry> levelsById = new HashMap<>();
    for (Levels.Entry level : Riiablo.files.Levels) {
      if (level != null) levelsById.put(level.Id, level);
    }

    int created = 0;
    for (int cursor = 0; cursor < queue.size(); cursor++) {
      int sourceLevelId = queue.get(cursor);
      Zone source = findZoneByLevelId(map, sourceLevelId);
      if (source == null || source.level == null) continue;

      for (Act2WarpEdge edge : edges) {
        if (edge.sourceLevelId != sourceLevelId || generated.contains(edge.destinationLevelId)) {
          continue;
        }
        Levels.Entry target = levelsById.get(edge.destinationLevelId);
        if (target == null) {
          Gdx.app.error(TAG, String.format(
              "Act2 dungeon target missing from Levels.txt: %d -> %d",
              sourceLevelId, edge.destinationLevelId));
          continue;
        }

        int[] placement = findDungeonPlacement(map, source, target, edge.mainIndex);
        Zone zone = createLinkedDungeonZone(map, target, diff, seed, placement[0], placement[1]);
        if (zone == null) continue;
        if (target.Id == LEVEL_ARCANESANCTUARY) {
          Act2ArcaneSanctuaryTopology topology = zone.arcaneSanctuaryTopology();
          Act2ArcaneSanctuaryLayout.Direction direction =
              Act2ArcaneSanctuaryLayout.fromLevelSeed(zone.levelSeed());
          Gdx.app.log(TAG, String.format(
              "Act2 Arcane Sanctuary topology: gameSeed=%d levelSeed=%d rooms=%d edges=%d summonerBranch=%d direction=%s rotation=%d branchDef=%d summonerDef=%d",
              seed, zone.levelSeed(), topology == null ? 0 : topology.rooms().size(),
              topology == null ? 0 : topology.edges().size(),
              topology == null ? -1 : topology.summonerBranch(), direction,
              direction.nativeRotation(), direction.branchPresetDef(),
              direction.summonerPresetDef()));
        }
        zone.generator = new BaseMapBuilderD2MOD() {{
          factory = Act2MapBuilderD2MOD.this.factory;
          socket = Act2MapBuilderD2MOD.this.socket;
        }}.createMonsterGenerator(socket);
        generated.add(target.Id);
        queue.add(target.Id);
        created++;
        Gdx.app.log(TAG, String.format(
            "Act2 linked dungeon created: %s(%d) <- %s(%d) visSlot=%d pos=(%d,%d)",
            target.LevelName, target.Id, source.level.LevelName, source.level.Id,
            edge.mainIndex, placement[0], placement[1]));
      }
    }

    TopologyReport report = validateAct2Topology(Riiablo.files.Levels, generated);
    Gdx.app.log(TAG, String.format(
        "Act2 linked dungeon summary: edges=%d created=%d generated=%d missingTargets=%d missingReverse=%d",
        report.edgeCount, created, generated.size(), report.missingTargets, report.missingReverse));
  }

  private Zone createLinkedDungeonZone(Map map, Levels.Entry level, int diff, int seed,
      int x, int y) {
    LvlPrest.Entry preset = findPreset(level.Id);
    BaseMapBuilderD2MOD base = new BaseMapBuilderD2MOD() {{
      factory = Act2MapBuilderD2MOD.this.factory;
      socket = Act2MapBuilderD2MOD.this.socket;
    }};

    final boolean presetLevel = level.DrlgType == 2 && preset != null;
    Zone zone;
    if (presetLevel) {
      int[] fileIds = new int[6];
      int count = Preset.getPresets(preset, fileIds);
      if (count <= 0) {
        Gdx.app.error(TAG, "Act2 linked preset has no DS1 files: " + level.LevelName);
        return null;
      }
      int levelSeed = NativeLevelSeed.forLevel(seed, level.Id);
      int select = fileIds[Math.floorMod(levelSeed, count)];
      if (!validPresetFile(preset, select)) {
        Gdx.app.error(TAG, String.format("Act2 linked preset file invalid: level=%d file=%d",
            level.Id, select));
        return null;
      }
      zone = base.createZoneWithPreset(map, level, preset, select, x, y, false);
    } else {
      int tilesX = Math.max(1, NativeDataTables.levelSizeX(level, diff, 1));
      int tilesY = Math.max(1, NativeDataTables.levelSizeY(level, diff, 1));
      int gridSizeX = nativeGridSize(tilesX);
      int gridSizeY = nativeGridSize(tilesY);
      // Keep the native dimensions exact.  The ordinary outdoor helper uses
      // a fixed 8x8 grid and truncates a maze whose size is not divisible by
      // eight, which leaves an unrendered/collision-free strip at the edge.
      zone = map.addZone(level, gridSizeX, gridSizeY,
          Math.max(1, tilesX / gridSizeX), Math.max(1, tilesY / gridSizeY));
      zone.setPosition(x, y);
      zone.town = false;
    }
    return zone;
  }

  private static int nativeGridSize(int tiles) {
    for (int size = Math.min(8, tiles); size >= 1; size--) {
      if (tiles % size == 0) return size;
    }
    return 1;
  }

  private static LvlPrest.Entry findPreset(int levelId) {
    for (LvlPrest.Entry preset : Riiablo.files.LvlPrest) {
      if (preset != null && preset.LevelId == levelId) return preset;
    }
    return null;
  }

  private static boolean validPresetFile(LvlPrest.Entry preset, int fileId) {
    return fileId >= 0 && fileId < preset.File.length
        && preset.File[fileId] != null && !preset.File[fileId].isEmpty()
        && preset.File[fileId].charAt(0) != '0';
  }

  private static int[] findDungeonPlacement(Map map, Zone source, Levels.Entry target,
      int mainIndex) {
    int targetWidth = Math.max(1, NativeDataTables.levelSizeX(target, source.diff, 1))
        * DT1.Tile.SUBTILE_SIZE;
    int targetHeight = Math.max(1, NativeDataTables.levelSizeY(target, source.diff, 1))
        * DT1.Tile.SUBTILE_SIZE;

    // The LvlWarp record owns the actual orientation; mainIndex is stable for
    // a seed but is not itself a cardinal direction.  Use it only to rotate
    // the deterministic candidate order, then test all four sides for overlap.
    int preferred = Math.floorMod(mainIndex, 4);
    for (int step = 0; step < 4; step++) {
      int direction = (preferred + step) & 3;
      int x, y;
      switch (direction) {
        case 0: x = source.x(); y = source.y() - targetHeight - DUNGEON_PLACEMENT_GAP; break;
        case 1: x = source.x() + source.width() + DUNGEON_PLACEMENT_GAP; y = source.y(); break;
        case 2: x = source.x(); y = source.y() + source.height() + DUNGEON_PLACEMENT_GAP; break;
        default: x = source.x() - targetWidth - DUNGEON_PLACEMENT_GAP; y = source.y(); break;
      }
      if (!overlapsAnyZone(map, x, y, targetWidth, targetHeight)) return new int[] {x, y};
    }

    // A dense table can exhaust all four adjacent positions.  Preserve the
    // graph by moving east in deterministic gap-sized bands until free.
    int x = source.x() + source.width() + DUNGEON_PLACEMENT_GAP;
    int y = source.y();
    int band = 2;
    while (overlapsAnyZone(map, x, y, targetWidth, targetHeight) && band < 1024) {
      x += DUNGEON_PLACEMENT_GAP * band++;
    }
    return new int[] {x, y};
  }

  private static boolean overlapsAnyZone(Map map, int x, int y, int width, int height) {
    for (Zone zone : map.zones) {
      if (zone == null) continue;
      if (x < zone.x() + zone.width() && x + width > zone.x()
          && y < zone.y() + zone.height() && y + height > zone.y()) return true;
    }
    return false;
  }

  static boolean isAct2Level(int levelId) {
    return levelId >= ACT2_LEVEL_FIRST && levelId <= ACT2_LEVEL_LAST;
  }

  private static boolean isAct2OutdoorLevel(int levelId) {
    return levelId >= LEVEL_LUTGHOLEIN && levelId <= LEVEL_CANYONOFTHEMAGI;
  }

  /** Returns only real teleport/entrance edges, not Vis-only sight links. */
  static List<Act2WarpEdge> discoverAct2WarpEdges(Iterable<Levels.Entry> levels) {
    HashMap<Integer, Levels.Entry> byId = new HashMap<>();
    for (Levels.Entry level : levels) if (level != null) byId.put(level.Id, level);
    List<Act2WarpEdge> result = new ArrayList<>();
    Set<String> seen = new HashSet<>();
    for (Levels.Entry source : byId.values()) {
      if (!isAct2Level(source.Id) || source.Vis == null || source.Warp == null) continue;
      int count = Math.min(8, Math.min(source.Vis.length, source.Warp.length));
      for (int i = 0; i < count; i++) {
        int targetId = source.Vis[i];
        if (source.Warp[i] < 0 || !isAct2Level(targetId)) continue;
        String key = source.Id + ":" + i + ":" + targetId;
        if (seen.add(key)) result.add(new Act2WarpEdge(source.Id, targetId, i));
      }
    }
    return result;
  }

  static TopologyReport validateAct2Topology(Iterable<Levels.Entry> levels,
      Set<Integer> generatedLevelIds) {
    HashMap<Integer, Levels.Entry> byId = new HashMap<>();
    for (Levels.Entry level : levels) if (level != null) byId.put(level.Id, level);
    TopologyReport report = new TopologyReport();
    Set<String> edgeKeys = new HashSet<>();
    for (Act2WarpEdge edge : discoverAct2WarpEdges(levels)) {
      edgeKeys.add(edge.sourceLevelId + ":" + edge.destinationLevelId);
    }
    for (Act2WarpEdge edge : discoverAct2WarpEdges(levels)) {
      report.edgeCount++;
      if (!byId.containsKey(edge.destinationLevelId)) report.missingTargets++;
      if (!generatedLevelIds.contains(edge.sourceLevelId)
          || !generatedLevelIds.contains(edge.destinationLevelId)) report.missingGenerated++;
      if (!edgeKeys.contains(edge.destinationLevelId + ":" + edge.sourceLevelId)) {
        report.missingReverse++;
      }
    }
    return report;
  }

  static final class Act2WarpEdge {
    final int sourceLevelId;
    final int destinationLevelId;
    final int mainIndex;

    Act2WarpEdge(int sourceLevelId, int destinationLevelId, int mainIndex) {
      this.sourceLevelId = sourceLevelId;
      this.destinationLevelId = destinationLevelId;
      this.mainIndex = mainIndex;
    }
  }

  static final class TopologyReport {
    int edgeCount;
    int missingTargets;
    int missingGenerated;
    int missingReverse;
  }

  /** Resolves the native Valley-of-Snakes -> Canyon placement contract. */
  static int[] resolveCanyonPlacement(int valleyX, int valleyY, int valleyWidth,
      int fallbackX, int fallbackY) {
    if (valleyWidth <= 0) return new int[] {fallbackX, fallbackY, 1};
    return new int[] {valleyX + valleyWidth, valleyY, 0};
  }

  /**
   * Installs Act II's native runtime destination table.  Levels.txt contains
   * only static links (mostly dungeon links); outdoor links are injected by
   * D2Common at runtime.  We reproduce the insertion algorithm instead of
   * guessing tile IDs, including the first-empty-slot rule used by
   * DRLG_SetWarpId.
   */
  void configureAct2OutdoorWarps(Map map) {
    if (map == null) return;

    IntMap<RuntimeWarpState> states = new IntMap<>();
    for (int i = 0; i < ACT2_OUTDOOR_LINKS.length; i++) {
      for (int side = 0; side < 2; side++) {
        int levelId = ACT2_OUTDOOR_LINKS[i][side];
        if (states.containsKey(levelId)) continue;
        Levels.Entry level = Riiablo.files.Levels.get(levelId);
        if (level == null) {
          Gdx.app.error(TAG, "Act2 warp level missing: " + levelId);
          continue;
        }
        states.put(levelId, new RuntimeWarpState(level.Vis, level.Warp));
      }
    }

    int configured = 0;
    for (int[] link : ACT2_OUTDOOR_LINKS) {
      RuntimeWarpState source = states.get(link[0]);
      RuntimeWarpState destination = states.get(link[1]);
      if (source == null || destination == null) continue;

      int sourceSlot = source.ensureDestination(link[1]);
      int destinationSlot = destination.ensureDestination(link[0]);
      if (sourceSlot < 0 || destinationSlot < 0) {
        Gdx.app.error(TAG, String.format(
            "Act2 warp slot exhausted: %d->%d sourceSlot=%d destinationSlot=%d",
            link[0], link[1], sourceSlot, destinationSlot));
        continue;
      }

      map.addWarpDestinationOverride(link[0], sourceSlot, link[1]);
      map.addWarpDestinationOverride(link[1], destinationSlot, link[0]);
      configured++;
      if (DEBUG_BUILD) {
        Gdx.app.debug(TAG, String.format(
            "Act2 native warp runtime link: %d[%d] <-> %d[%d]",
            link[0], sourceSlot, link[1], destinationSlot));
      }
    }
    Gdx.app.log(TAG, String.format("Act2 native warp table configured: links=%d/%d",
        configured, ACT2_OUTDOOR_LINKS.length));
  }

  /**
   * Pairs the actual special-wall cells emitted by DS1/native exports.  Warp
   * entities use the destination zone's reverse special ID, matching the
   * behaviour expected by WarpInteractor.
   */
  void linkNativeWarpSpecials(Map map) {
    if (map == null) return;
    int linked = 0;
    int missingZone = 0;
    int missingReverse = 0;
    for (Zone source : new Array.ArrayIterator<>(map.zones)) {
      if (source == null || source.level == null || source.specials == null) continue;
      for (IntMap.Entry<DS1.Cell> entry : source.specials.entries()) {
        DS1.Cell sourceCell = entry.value;
        if (sourceCell == null || !Map.ID.WARPS.contains(sourceCell.id)) continue;
        // A Vis entry can describe a neighbouring level that is only in the
        // sight graph.  D2Common creates a warp only when the corresponding
        // LvlWarp slot is valid; do not turn a visibility marker into a
        // playable entrance.
        if (source.level.Warp == null || sourceCell.mainIndex < 0
            || sourceCell.mainIndex >= source.level.Warp.length
            || source.level.Warp[sourceCell.mainIndex] < 0) continue;
        int destinationLevelId = map.getWarpDestinationOverride(
            source.level.Id, sourceCell.mainIndex);
        if (destinationLevelId <= 0 && source.level.Vis != null
            && sourceCell.mainIndex >= 0
            && sourceCell.mainIndex < source.level.Vis.length) {
          destinationLevelId = source.level.Vis[sourceCell.mainIndex];
        }
        if (destinationLevelId <= 0) continue;

        Zone destination = findZoneByLevelId(map, destinationLevelId);
        if (destination == null) {
          missingZone++;
          if (missingZone <= 16) {
            Gdx.app.log(TAG, String.format(
                "Act2 warp missing zone: %s(%d) mainIndex=%d target=%d",
                source.level.LevelName, source.level.Id, sourceCell.mainIndex,
                destinationLevelId));
          }
          continue;
        }

        DS1.Cell destinationCell = findReverseWarp(map, destination, source.level.Id);
        if (destinationCell == null) {
          missingReverse++;
          if (missingReverse <= 16) {
            Gdx.app.log(TAG, String.format(
                "Act2 warp missing reverse: %s(%d) -> %s(%d) mainIndex=%d",
                source.level.LevelName, source.level.Id,
                destination.level.LevelName, destination.level.Id,
                sourceCell.mainIndex));
          }
          continue;
        }

        source.setWarp(sourceCell.id, destinationCell.id);
        linked++;
      }
    }
    Gdx.app.log(TAG, String.format(
        "Act2 native warp special summary: linked=%d missingZone=%d missingReverse=%d",
        linked, missingZone, missingReverse));
  }

  private static Zone findZoneByLevelId(Map map, int levelId) {
    for (Zone zone : map.zones) {
      if (zone != null && zone.level != null && zone.level.Id == levelId) return zone;
    }
    return null;
  }

  private static DS1.Cell findReverseWarp(Map map, Zone destination, int sourceLevelId) {
    if (destination.specials == null) return null;
    for (IntMap.Entry<DS1.Cell> entry : destination.specials.entries()) {
      DS1.Cell cell = entry.value;
      if (cell == null || !Map.ID.WARPS.contains(cell.id)) continue;
      if (destination.level.Warp == null || cell.mainIndex < 0
          || cell.mainIndex >= destination.level.Warp.length
          || destination.level.Warp[cell.mainIndex] < 0) continue;
      int target = map.getWarpDestinationOverride(destination.level.Id, cell.mainIndex);
      if (target <= 0 && destination.level.Vis != null
          && cell.mainIndex >= 0 && cell.mainIndex < destination.level.Vis.length) {
        target = destination.level.Vis[cell.mainIndex];
      }
      if (target == sourceLevelId) return cell;
    }
    return null;
  }

  /** Small Java equivalent of DRLG_SetWarpId's slot-selection portion. */
  static int findRuntimeWarpSlot(int[] vis, int[] warp, int destinationLevelId) {
    if (vis == null || warp == null) return -1;
    int count = Math.min(8, Math.min(vis.length, warp.length));
    for (int i = 0; i < count; i++) {
      if (vis[i] == destinationLevelId) return i;
    }
    for (int i = 0; i < count; i++) {
      if (vis[i] == 0 && warp[i] == -1) return i;
    }
    return -1;
  }

  private static final class RuntimeWarpState {
    final int[] vis = new int[8];
    final int[] warp = new int[8];

    RuntimeWarpState(int[] sourceVis, int[] sourceWarp) {
      for (int i = 0; i < vis.length; i++) {
        vis[i] = sourceVis != null && i < sourceVis.length ? sourceVis[i] : 0;
        warp[i] = sourceWarp != null && i < sourceWarp.length ? sourceWarp[i] : -1;
      }
    }

    int ensureDestination(int destinationLevelId) {
      int slot = findRuntimeWarpSlot(vis, warp, destinationLevelId);
      if (slot >= 0) vis[slot] = destinationLevelId;
      return slot;
    }
  }

}
